# Basic
title: い寻常づ
subtitle: 博客
description: 众里寻Ta千百度，蓦然回首，云深不知处。
# 头像里面的标题
avatarTitle: い寻常づ
# 头像里面的描述
avatarDesc: 背篓少年
url: "https://xc1218.github.io"

# Comment
comment:
    disqus: leopard
    # gitment: xc1218 // 需要修改 comments.html中的client_id和client_secret
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    weibo: xc-2333 
    github: xc1218
    # zhihu: 暮雨
    # juejin: xxx
    jianshu: 晴天蒙雨
    # twitter: 
    mail: m1657642978@gmail.com


# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: xxxx  

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: xxxx  
    host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://xc1218.github.io/
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


